env:
  global:
    - TF_VERSION=0.12.23
    - GOOGLE_APPLICATION_CREDENTIALS=sa-gcp.json
sudo: required
language: bash
before_install:
  - openssl aes-256-cbc -K $encrypted_6d375b8dd7c7_key -iv $encrypted_6d375b8dd7c7_iv -in sa-gcp.json.enc -out sa-gcp.json -d
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - gcloud auth activate-service-account travis-terraform-tests@fleet-goal-232910.iam.gserviceaccount.com --key-file=sa-gcp.json
  - make fmt
  - make validate
  - make test
  - make nat_verify
  - make destroy
